<template>
  <q-dialog v-model="isVisible" persistent>
    <q-card style="min-width: 400px">
      <q-card-section class="row items-center">
        <q-avatar icon="add_circle" color="primary" text-color="white" />
        <span class="q-ml-sm text-h6">새 슬라이드 생성</span>
      </q-card-section>

      <q-card-section>
        <div class="text-body1">
          <strong>{{ lessonTitle }}</strong
          >의 <strong>{{ slideNumber }}번째 슬라이드</strong>가 존재하지 않습니다.
        </div>
        <div class="text-caption text-grey-6 q-mt-sm">새 슬라이드를 생성하시겠습니까?</div>
      </q-card-section>

      <q-card-section v-if="showOptions" class="q-pt-none">
        <div class="text-subtitle2 q-mb-sm">슬라이드 유형 선택:</div>
        <q-option-group v-model="selectedType" :options="slideTypes" color="primary" inline />

        <div class="text-subtitle2 q-mb-sm q-mt-md">Vue 컴포넌트 파일 정보:</div>
        <div class="text-caption text-grey-6 q-mb-sm">
          저장 경로: <strong>src/components/slides/</strong>
        </div>
        <div class="text-subtitle2 q-mb-sm q-mt-md">파일명:</div>
        <q-input
          v-model="customFileName"
          label="파일명 (확장자 제외)"
          outlined
          dense
          :rules="[
            (val) => !!val || '파일명을 입력해주세요',
            (val) =>
              /^[a-z0-9가-힣_-]+$/.test(val) ||
              '소문자, 숫자, 한글, 언더스코어, 하이픈만 사용 가능합니다',
          ]"
          hint="예: slide-1-2, my-slide, 슬라이드제목"
          class="q-mb-sm"
        />
        <div class="text-caption text-grey-6">
          생성될 파일: <strong>{{ customFileName || autoGeneratedFileName }}.vue</strong>
        </div>
      </q-card-section>

      <q-card-actions align="right">
        <q-btn flat label="취소" color="grey" @click="handleCancel" />
        <q-btn unelevated label="생성" color="primary" @click="handleCreate" />
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';

interface Props {
  modelValue: boolean;
  lessonTitle: string;
  slideNumber: number;
  showOptions?: boolean;
}

interface Emits {
  (e: 'update:modelValue', value: boolean): void;
  (e: 'create', slideType: string, componentFileName: string): void;
  (e: 'cancel'): void;
}

const props = withDefaults(defineProps<Props>(), {
  showOptions: true,
});

const emit = defineEmits<Emits>();

const isVisible = computed({
  get: () => props.modelValue,
  set: (value) => emit('update:modelValue', value),
});

const selectedType = ref('markdown');
const customFileName = ref('');

// 자동 생성된 파일명
const autoGeneratedFileName = computed(() => {
  // 첫 번째 슬라이드인 경우 Chapter 컴포넌트
  if (props.slideNumber === 1) {
    return `Chapter-1`;
  } else {
    return `slide-${props.slideNumber}`;
  }
});

const slideTypes = [
  { label: 'Markdown 슬라이드', value: 'markdown' },
  { label: '빈 슬라이드', value: 'empty' },
  { label: '템플릿 슬라이드', value: 'template' },
];

const handleCreate = () => {
  const fileName = customFileName.value.trim() || autoGeneratedFileName.value;
  emit('create', selectedType.value, fileName);
  isVisible.value = false;
};

const handleCancel = () => {
  emit('cancel');
  isVisible.value = false;
};
</script>

<style scoped>
.q-card {
  border-radius: 12px;
}
</style>
