# DISABLED: Azure Static Web Apps deployment
# Using Azure App Service instead
name: Azure Static Web Apps CI/CD (DISABLED)

on:
  # Disabled - no triggers
  workflow_dispatch: # Manual trigger only

jobs:
  build_and_deploy_job:
    if: false # Always skip this job
    runs-on: ubuntu-latest
    name: Build and Deploy Job (DISABLED)
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build
        env:
          NODE_ENV: production

      - name: Clean up for Azure deployment
        run: |
          echo "Cleaning up for Azure Static Web Apps deployment..."

          # Remove all PDF files
          find dist/ -name "*.pdf" -delete

          # Remove large image files
          find dist/images -name "*.png" -size +500k -delete

          # Remove test files
          rm -rf dist/test-*

          # Remove development files
          rm -rf dist/.DS_Store

          # Remove unnecessary generated files
          rm -rf dist/generated/template-based-converter-cjs-generated
          rm -rf dist/generated/slides-sidebar

          # Remove large HTML files
          find dist/ -name "*.html" -size +100k -delete

          # Keep only essential slides (first 10)
          mkdir -p dist/generated/slides-essential
          find dist/generated/slides -name "slide-*.html" | head -10 | xargs -I {} cp {} dist/generated/slides-essential/
          rm -rf dist/generated/slides
          mv dist/generated/slides-essential dist/generated/slides

          # Remove any remaining large files
          find dist/ -type f -size +1M -delete

          # Remove unnecessary directories
          rm -rf dist/scripts
          rm -rf dist/tests
          rm -rf dist/playwright-report

          # Remove large assets
          find dist/assets -name "*.js" -size +500k -delete
          find dist/assets -name "*.css" -size +100k -delete

          echo "Final dist size:"
          du -sh dist/
          echo "Files in dist:"
          find dist/ -type f | wc -l

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          skip_app_build: true
          skip_api_build: true
          app_location: '/dist'
          output_location: ''
          deployment_environment: production
          app_build_command: ''
          app_artifact_location: 'dist'

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'close'
