name: Deploy to Azure App Service

on:
  push:
    branches: [master]
  workflow_dispatch: # Manual trigger

# 중복 실행 방지
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: slide-view-app-new
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Vue.js app
        run: npm run build
        
      - name: Build slides
        run: npm run build-slides
        
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
          
      - name: Deploy success
        run: |
          echo "🚀 배포 완료!"
          echo "🌐 URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          echo "📱 Azure Portal: https://portal.azure.com/#@coachingware.onmicrosoft.com/resource/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/ai-seminar-rg/providers/Microsoft.Web/sites/${{ env.AZURE_WEBAPP_NAME }}/overview"
